# Generated by Django 2.2.12 on 2020-05-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosuser',
            options={'verbose_name': 'Datos del Usuario', 'verbose_name_plural': 'Informacíon'},
        ),
        migrations.AlterModelOptions(
            name='detaroles',
            options={'verbose_name': 'Roles de Usuario', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='habiluser',
            options={'verbose_name': 'Habilidades del Usuario', 'verbose_name_plural': 'Competencias'},
        ),
        migrations.AlterModelOptions(
            name='rates',
            options={'verbose_name': 'Nivel de Habilidad', 'verbose_name_plural': 'Niveles de Usuario'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Perfiles de Usuario', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
