# Generated by Django 2.2.12 on 2020-05-13 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdata', '0005_auto_20200513_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategProye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguaje', models.CharField(max_length=45, verbose_name='Lenguaje')),
                ('motorDB', models.CharField(max_length=155, verbose_name='Motor de Base de Datos')),
                ('arquitectura', models.CharField(max_length=255, verbose_name='Arquitectura')),
            ],
            options={
                'verbose_name': 'Categoria del Proyecto',
                'verbose_name_plural': 'Información Especifica del Proyecto',
            },
        ),
        migrations.CreateModel(
            name='TipoDocu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombTiDoc', models.CharField(max_length=45, verbose_name='Nombre Tipo Documento')),
            ],
            options={
                'verbose_name': 'Tipos de Documento',
                'verbose_name_plural': 'Tipos de Documento',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombProy', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('descProy', models.TextField(max_length=255, verbose_name='Descripción del Proyecto')),
                ('imgProy', models.ImageField(default='proyecto.png', upload_to=None, verbose_name='Foto del Proyecto')),
                ('fechaIni', models.DateTimeField(null=True, verbose_name='Iniciado el')),
                ('fechaFin', models.DateTimeField(null=True, verbose_name='Finalizado el')),
                ('urlRepo', models.CharField(max_length=255, verbose_name='Dirección Repositorio')),
                ('estaProy', models.CharField(max_length=45, verbose_name='Estado del Proyecto')),
                ('idCategProye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.CategProye', verbose_name='Identificador de Categoria')),
            ],
            options={
                'verbose_name': 'Descripción Proyectos',
                'verbose_name_plural': 'Descripción Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombDocu', models.CharField(max_length=155, verbose_name='Nombre del Documento')),
                ('pathDocu', models.FileField(upload_to=None, verbose_name='Documento')),
                ('idProyectos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Identificador de Proyectos')),
                ('idTipoDocu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.TipoDocu', verbose_name='Identificador de Tipo Documento')),
                ('idUsuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='Identificador de Usuario')),
            ],
            options={
                'verbose_name': 'Documentos',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
