# Generated by Django 2.2.12 on 2020-05-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='fechaFin',
            field=models.DateField(null=True, verbose_name='Finalizado el'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='fechaIni',
            field=models.DateField(null=True, verbose_name='Iniciado el'),
        ),
    ]
